language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install: "sudo apt-get install -y libgmp-dev libgmp10 libgmp3-dev libgmp3c2 libgmpxx4ldbl python-gmpy && sudo pip install nose"
# command to run tests:
script: "make check"
