import unittest
from time import time
from fibonacci import fib_generator

"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

def problem002():
    total = 0
    for i in fib_generator(1, 2):
        if i > 4000000:
            return total
        if i % 2 == 0:
            total += i

class TestProblem002(unittest.TestCase):
    def runTest(self):
        self.start = time()
        self.assertEqual(4613732, problem002(), "Answer to #2 is wrong.")
        self.stop = time()
        self.assertLess(self.stop - self.start, 60, "Problem #2 took over 60 seconds.")

if __name__ == "__main__":
    start = time()
    answer = problem002()
    print 2, (time() - start), answer
